language: java
jdk:
- oraclejdk8
script:
- mvn install
- mvn compile
- mvn test
before_install:
- git clone https://github.com/samutamm/PaivanUutiset.git
- cd PaivanUutiset
- mvn install
- cd ..
- git clone https://github.com/samutamm/HackerNewsUutiset.git
- cd HackerNewsUutiset
- mvn install
- cd ..
after_success:
- mvn clean heroku:deploy -Dheroku.appName=murmuring-plateau-7361
- mvn cobertura:cobertura coveralls:report
env:
  global:
    secure: o+gANkwV+OKCz8KGa0tDA44JBTvlSoLUDzBeXzxnWvRb9d2JbWI/HbG/MQVLjjhN+L/bn2zE15OTxE3nPyZB1Ze8HlfsrpfmPYCb2vxNv478VeiMgPmi3xaLmRWiUGsh9dalGlZ833w9CmkacCA77nOquT6EW31rl2Kg++vCQ/HqXjOcIOknXrLw2JKdbwMkbJM5pfL0tVZ/+Hb2YnqrkiOdvZ5KYdSeKDUh6omgkA1AaQwaIDg9H64loxywibAyGr9EvoMYazOOGL8CrBbdpcC8EKf34BcdqbQY4uvdMLXb2sdjCPX65z80I9gPXx8Im8KptyT6UUt469C/s5KpeNbnBq0Xx/0C0XAfLGMrbtBZLtEgLvO0AKDn91aQDs/AgBLKTULva3JJAbtfbssQj8vA8vEeZst2+t1LCpzpnEjEgiixVsR4vAGcGRlSAEalGXGsXyR4L6aaE5TotANeniq7dbPveUCM01HZzKoOAkI1Gm25lEubsW70M8gMLQwcu9H0kD7pYutONA6/a9p8HUAPJp9wQWPSym02mSDbGqk8QPih3CwO5/KJTQmBv2a/qni/0g1GTeFOy1GrSQ7xC6aNARFAX6hcLmX89Kgh4BJbtM4fv1QQa3cC6cPlPKElOeF3jyfwVgt3muuowKOdCnC8zJcCETEnst3mpS6nKrM=
