language: java
jdk:
  - oraclejdk8
script:
- mvn install
- mvn compile
- mvn test
before_install:
- git clone https://github.com/samutamm/PaivanUutiset.git
- cd PaivanUutiset
- mvn install
- cd ..
- git clone https://github.com/samutamm/HackerNewsUutiset.git
- cd HackerNewsUutiset
- mvn install
- cd ..
after_success:
  - mvn clean heroku:deploy -Dheroku.appName=murmuring-plateau-7361
